### ISSUE TITLE
Make the player character move to where you click

### ISSUE THREAD

**Issue by Torakko** [ravertass/PixelHunter1995#10] opened 2020-06-25 20:11 UTC

**Comment by feha** [comment] 2020-06-25 22:39
Feels like a duplicate of #7 ?

**Comment by ravertass** [comment] 2020-06-27 09:54
@feha I added some more text to #7 for clarification. My idea is that you can start by just making the PC move in some super-basic way, e.g. constantly to the right.

I'm trying to write some super-basic tasks to begin with, since not everyone are familiar with C# or MonoGame, just to make it easier to start contributing. Over time tasks could probably be more complete features.

**Closed as completed** 2020-07-12 17:16 UTC
